### Get all students
GET http://localhost:4000/students

### Create a student
POST http://localhost:4000/students
Content-Type: application/json

{
  "firstname": "Donald",
  "lastname": "Trump",
  "birthday": "1990-02-14",
  "address": "USA",
  "num_courses": 4
}