### Get all students
GET http://localhost:4000/students

### Get one student
GET http://localhost:4000/students/3000

### Create a student
POST http://localhost:4000/students
Content-Type: application/json

{
  "firstname": "Arnold",
  "lastname": "D'Artagnan",
  "birthday": "1912-02-14",
  "address": "France",
  "num_courses": 6
}

### Update a student
PUT http://localhost:4000/students/5
Content-Type: application/json

{
  "firstname": "Jack",
  "lastname": "Hopkins",
  "birthday": "1971-07-07",
  "address": "USA",
  "num_courses": 5
}

### Delete a student
DELETE http://localhost:4000/students/5